services:
  social_app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
      - ./logs:/app/logs
    command: > 
      sh -c "
      python manage.py wait_for_db
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: celery-worker
    build:
      context: .
    command: celery -A social_media worker --loglevel=info
    volumes:
      - ./:/social_app
    env_file:
      - .env
    depends_on:
      - social_app
      - redis

  redis:
    image: redis:7.2.5-alpine3.19
    ports:
      - "6379:6379"



  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA


volumes:
  my_db:
  my_media:
